spring.application.name=Instagram

spring.datasource.url=jdbc:postgresql://localhost:5432/instagram
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=200MB

cloudinary.cloud_name=dbqalriqr
cloudinary.api_key=799448689749953
cloudinary.api_secret=T1LOJVVVbqoDZMNvg4sIi9N75Y8

jwt.secret=instagramcloneinstagramcloneinstagramclone12345
